#pragma once
#include <stm32f407xx_types.h>

/* Public defines ------------------------------------------------------------*/
typedef enum
{
    IRQ_NO_NMI = -2,
    IRQ_NO_HARDFAULT,
    IRQ_NO_MEMMANAGE,
    IRQ_NO_BUSFAULT,
    IRQ_NO_USAGEFAULT,
    IRQ_NO_SVC,
    IRQ_NO_DEBUGMON,
    IRQ_NO_PENDSV,
    IRQ_NO_SYSTICK,
    IRQ_NO_WWDG,
    IRQ_NO_PVD,
    IRQ_NO_TAMP_STAMP,
    IRQ_NO_RTC_WKUP,
    IRQ_NO_RCC = 12,
    IRQ_NO_EXTI0,
    IRQ_NO_EXTI1,
    IRQ_NO_EXTI2,
    IRQ_NO_EXTI3,
    IRQ_NO_EXTI4,
    IRQ_NO_DMA1_STREAM0,
    IRQ_NO_DMA1_STREAM1,
    IRQ_NO_DMA1_STREAM2,
    IRQ_NO_DMA1_STREAM3,
    IRQ_NO_DMA1_STREAM4,
    IRQ_NO_DMA1_STREAM5,
    IRQ_NO_DMA1_STREAM6,
    IRQ_NO_ADC,
    IRQ_NO_CAN1_TX,
    IRQ_NO_CAN1_RX0,
    IRQ_NO_CAN1_RX1,
    IRQ_NO_CAN1_SCE,
    IRQ_NO_EXTI9_5,
    IRQ_NO_TIM1_BRK_TIM9,
    IRQ_NO_TIM1_UP_TIM10,
    IRQ_NO_TIM1_TRG_COM_TIM11,
    IRQ_NO_TIM1_CC,
    IRQ_NO_TIM2,
    IRQ_NO_TIM3,
    IRQ_NO_TIM4,
    IRQ_NO_I2C1_EV,
    IRQ_NO_I2C1_ER,
    IRQ_NO_I2C2_EV,
    IRQ_NO_I2C2_ER,
    IRQ_NO_SPI1,
    IRQ_NO_SPI2,
    IRQ_NO_USART1,
    IRQ_NO_USART2,
    IRQ_NO_USART3,
    IRQ_NO_EXTI15_10,
    IRQ_NO_RTC_ALARM,
    IRQ_NO_OTG_FS_WKUP,
    IRQ_NO_TIM8_BRK_TIM12,
    IRQ_NO_TIM8_UP_TIM13,
    IRQ_NO_TIM8_TRG_COM_TIM14,
    IRQ_NO_TIM8_CC,
    IRQ_NO_DMA1_STREAM7,
    IRQ_NO_FSMC,
    IRQ_NO_SDIO,
    IRQ_NO_TIM5,
    IRQ_NO_SPI3,
    IRQ_NO_UART4,
    IRQ_NO_UART5,
    IRQ_NO_TIM6_DAC,
    IRQ_NO_TIM7,
    IRQ_NO_DMA2_STREAM0,
    IRQ_NO_DMA2_STREAM1,
    IRQ_NO_DMA2_STREAM2,
    IRQ_NO_DMA2_STREAM3,
    IRQ_NO_DMA2_STREAM4,
    IRQ_NO_ETH,
    IRQ_NO_ETH_WKUP,
    IRQ_NO_CAN2_TX,
    IRQ_NO_CAN2_RX0,
    IRQ_NO_CAN2_RX1,
    IRQ_NO_CAN2_SCE,
    IRQ_NO_OTG_FS,
    IRQ_NO_DMA2_STREAM5,
    IRQ_NO_DMA2_STREAM6,
    IRQ_NO_DMA2_STREAM7,
    IRQ_NO_USART6,
    IRQ_NO_I2C3_EV,
    IRQ_NO_I2C3_ER,
    IRQ_NO_OTG_HS_EP1_OUT,
    IRQ_NO_OTG_HS_EP1_IN,
    IRQ_NO_OTG_HS_WKUP,
    IRQ_NO_OTG_HS,
    IRQ_NO_DCMI,
    IRQ_NO_CRYP,
    IRQ_NO_HASH_RNG,
    IRQ_NO_FPU
} irq_number_t;

/* Public types --------------------------------------------------------------*/

/* Public function prototypes ------------------------------------------------*/
int enable_irq(irq_number_t irq);

int disable_irq(irq_number_t irq);

int config_irq_set_priority(irq_number_t irq, uint8_t priority);
